name: Deploy Web API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: windows-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Download latest artifact
        uses: actions/download-artifact@v4
        with:
          path: ./publish

      - name: Deploy to Windows server
        env:
          WIN_USER: ${{ github.event.inputs.environment == 'staging' && secrets.WIN_USER_STAGING || secrets.WIN_USER_PRODUCTION }}
          WIN_PASS: ${{ github.event.inputs.environment == 'staging' && secrets.WIN_PASS_STAGING || secrets.WIN_PASS_PRODUCTION }}
        run: |
          $artifactDir = Get-ChildItem -Directory ./publish | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          $session = New-PSSession -ComputerName "${{ github.event.inputs.environment }}-server" -Credential (New-Object PSCredential($env:WIN_USER, (ConvertTo-SecureString $env:WIN_PASS -AsPlainText -Force)))
          Copy-Item -Path $artifactDir.FullName\* -Destination "C:\inetpub\wwwroot\myapp" -Recurse -ToSession $session
          Invoke-Command -Session $session -ScriptBlock { Restart-Service -Name "myapp" }
          Remove-PSSession $session