name: Build and Publish Web API
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release
        
      - name: Publish
        run: dotnet publish --no-build --configuration Release --output ./publish

      - name: Set artifact name
        id: artifact_name
        run: echo "ARTIFACT_NAME=webapi-artifact-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./publish